theme: minima
title: My Website
author: GitHub User s338641178
email: spras3@ocdsb.ca
description: > My Website
 This is my fantastice Website where I will be writing a blog!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


